server:
  port: 8080
spring:
  application:
    name: consumer # åº”ç”¨åç§°

eureka:
  client:
    service-url: # EurekaServeråœ°å€
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true # å½“å…¶å®ƒæœåŠ¡è·å–åœ°å?æ—¶æä¾›ipè€Œä¸æ˜¯hostname
    ip-address: 127.0.0.1 # æŒ‡å®šè‡ªå·±çš„ipä¿¡æ¯ï¼Œä¸æŒ‡å®šçš„è¯ä¼šè‡ªå·±å¯»æ‰?

