server:
  port: 10086
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false # æ˜¯å¦æ³¨å†Œè‡ªå·±çš„ä¿¡æ¯åˆ°EurekaServerï¼Œé»˜è®¤æ˜¯true
    fetch-registry: false # æ˜¯å¦æ‹‰å–å…¶å®ƒæœåŠ¡çš„ä¿¡æ¯ï¼Œé»˜è®¤æ˜¯true
    service-url: # EurekaServerçš„åœ°å?ï¼Œç°åœ¨æ˜¯è‡ªå·±çš„åœ°å?ï¼Œå¦‚æœæ˜¯é›†ç¾¤ï¼Œéœ€è¦åŠ ä¸Šå…¶å®ƒServerçš„åœ°å?ã€?
      defaultZone: http://127.0.0.1:${server.port}/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}