
#连接池
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/dcy?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: "0325"

# 别名扫描
mybatis:
  type-aliases-package: com.springboot.pojo
  mapper-locations: mappers/*.xml
